apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::618150829136:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IAE7188EJN1D
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-29T15:04:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6122"
  uid: 9cc0065d-466e-4fe8-924a-cd4853d981b2
