apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::618150829136:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-29T01:39:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1655"
  uid: 3dcdc164-d36b-4de6-98bc-9f486c6bc768
