apiVersion: v1
data:
  mapRoles: "- groups:\n    - system:masters\n    rolearn: arn:aws:iam::618150829136:role/UdacityFlaskDeployCBKubectlRole\n
    \   username: build  \n  - groups:\n    - system:bootstrappers\n    - system:nodes\n
    \   rolearn: arn:aws:iam::618150829136:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XL6Q3PB524FB\n
    \   username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-01T15:38:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7057"
  uid: fa204756-d96d-443b-9524-e197cc74c2c9
